language: go

matrix:
  include:
    - go: 1.10.x
      install:
        - go get golang.org/x/tools/go/loader
        - go get github.com/gojuno/generator
    - go: 1.11.x

env:
  - GO111MODULE=on

script:
  - make test